repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.280"
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
