channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  - pytorch>=1.13.1
  - pytorch-cuda=11.7
  - transformers>=4.26.0
  - datasets>=2.9.0
  - pytorch-lightning>=1.9.0

  - scikit-learn
  - pandas
  - wandb

  - rich
  - typer
  - loguru
  - pyyaml

  - black
  - isort
  - flake8
  - flake8-bugbear
  - mypy
  - ipywidgets
  - pre-commit

  - pip:
      - bitsandbytes; platform_system=='Linux'
      - pytorch_optimizer
      - ruff
