channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  - pytorch>=2.0
  - pytorch-cuda=11.8
  - transformers>=4.27.0
  - datasets>=2.10.0
  - pytorch-lightning>=2.0.0

  - scikit-learn
  - pandas
  - wandb

  - rich
  - typer
  - loguru
  - pyyaml

  - black
  - isort
  - flake8
  - flake8-bugbear
  - ruff
  - mypy
  - ipywidgets
  - pre-commit

  - pip:
      - bitsandbytes; platform_system=='Linux'
      - pytorch_optimizer
